package com.example.backend.Enums;
public enum NotificationType { ARTICLE_SUBMITTED, REVIEW_INVITED, REVIEW_ACCEPTED, REVIEW_DECLINED, REVIEW_COMPLETED, REVISION_REQUESTED, ARTICLE_ACCEPTED, ARTICLE_REJECTED, ARTICLE_PUBLISHED, ISSUE_PUBLISHED }
